### ISSUE TITLE
contains `<![CDATA[ ` without a corresponding `]]>` .

### ISSUE THREAD

**Issue by eshellman** [gutenbergbooks/30#1]
The new HTM file causes the xml parser to crash so badly that ebookmaker can't even emit a CRITICAL log: the xml parser just hangs.

The problem is that it contains `<![CDATA[ ` without a corresponding `]]>` .

**Comment by eshellman** [comment]
on closer examination a CRITICAL message is indeed logged, it just takes a while

**Comment by asylumcs** [comment]
This book does not use a CDATA section.
