### ISSUE TITLE
various typos

### ISSUE THREAD

**Issue by smichr** [gutenbergbooks/30#2]
I checked this text against the Gutenberg/10 version and found the following differences. I list the Gutenberg/10 version on top and Gutenberg/30 version on the bottom: the difference is to the left of "#" and the text to the right of the "#" is for context.

### typos?
Gen 13:4
made #there at the first: and there Abram cal
make #there at the first: and there Abram cal

Gen 28:2
daughters #of Laban thy mother's brother.
daughers #of Laban thy mother's brother.

Gen 28:8
daughters #of Canaan; 
daughers #of Canaan;

Ex 2:9
woman #took the child, and nursed it.
women #took the child, and nursed it.

Deut 7:25
therein: #for it is an abomination to the LOR
therin: #for it is an abomination to the LORD

Jos 1:7
whithersoever #thou goest.
withersoever #thou goest.

1Kings 22:22
persuade #him, and prevail also: go forth, an
persude #him, and prevail also: go forth, and

2 Kings 8:16
Jehoshaphat #king of Judah began to reign.
Je hoshaphat #king of Judah began to reign.

2 Chron 13:8
you #golden calves, which Jeroboam made you f
your #golden calves, which Jeroboam made you 

Est 4:11
woman, #shall come unto the king into the inn
women, #shall come unto the king into the inn

Is 60:15
hast #been forsaken and hated, so that no man
has #been forsaken and hated, so that no man 

Jer 34:16
ye #had set at liberty at their pleasure, to 
he #had set at liberty at their pleasure, to 

Ob 1:7
they that #eat thy bread have laid a wound un
that they #eat thy bread have laid a wound un

Jon 4:11
than #sixscore thousand persons
then #sixscore thousand persons

Mat 5:21
by #them of old time, Thou shalt not kill; an
of #them of old time, Thou shalt not kill; an

### extra words
Jer 39:10
#of the poor of the land to be vinedressers a
of the door #of the poor of the land to be vi

### missing word?
Est 7:8
the #king's mouth, they covered Haman's face.
#king's mouth, they covered Haman's face.

Est 7:9
had #spoken good for the king, standeth in th
#spoken good for the king, standeth in the ho

### Good changes

Gen 4:22
instructer #of every artificer in brass and i
instructor #of every artificer in brass and i

1 Cor 4:15
instructers #in Christ, yet have ye not many
instructors #in Christ, yet have ye not many 

### Arcaic spelling

Gen 30:37
chestnut #tree; and pilled white strakes in t
chesnut #tree; and pilled white strakes in th

### Questionable

John 11:16
fellow disciples, #Let us also go, that we ma
fellowdisciples, #Let us also go, that we may

**Comment by asylumcs** [comment]
Thank you for your report. I will let you know of our progress.

**Comment by asylumcs** [comment]
Did you check PG #30 against the Pure Cambridge Edition (1900) as first reported, or against PG #10 as the issue reads now?

**Comment by smichr** [comment]
PURE and gutenberg/10 are the same in all cases except for 1 Cor 4:15, Gen 30:37 and John 11:16 which all three agree with gutenberg/30

**Comment by asylumcs** [comment]
Thank you for your corrections. The Errata Team reports they have been incorporated. I am closing this issue.
