### ISSUE TITLE
instructer->instructor

### ISSUE THREAD

**Issue by smichr** [gutenbergbooks/30#3]
In 1:004:022 and 46:004:015, "instructer" could be "instructor" to match that in 45:002:020.

https://www.askdifference.com/instructer-vs-instructor/#:~:text=%22Instructer%22%20is%20incorrect%2C%20while%20%22Instructor%2C%22%20denoting%20one,who%20teaches%20or%20trains%2C%20is%20the%20proper%20spelling.

**Comment by asylumcs** [comment]
corrected. Thank you..
