### ISSUE TITLE
Jeremiah 32:5 - end of a question, so use "?"

### ISSUE THREAD

**Issue by smichr** [gutenbergbooks/30#4]
I would have got this one wrong, but as pointed out [here](https://av1611.com/forums/showthread.php?t=82#:~:text=Since%20%E2%80%9CWherefore%E2%80%9D%20is%20the%20beginning%20of) verse Jer 32:5 is the end of a question which starts with the interrogative, "Wherefore". It is akin to writing "Why do you say I am going to the store?" 

You can search for other "Wherefore <verb form>...?" to see that they end in a question mark. This one is trickier because (like the example I gave) the question is in reference to a statement (not a question, like in 1:018:013).

**Comment by asylumcs** [comment]
Corrected. Thank you.
