### ISSUE TITLE
comma after "saith"

### ISSUE THREAD

**Issue by smichr** [gutenbergbooks/30#6]
In the following, `46:015:027 For he hath put all things under his feet. But when he saith`, a comma after "saith" is consistent with commas added before the phrase being quoted, agrees with the Authorized Version, and agrees with ChatGPT suggestion for edit:

```
The punctuation in your sentence is mostly correct, but it could be clearer with a slight adjustment. Here’s a revised version:

"But when he saith, 'All things are put under him,' it is manifest that he is excepted, who did put all things under him."

This change adds a comma after "saith" for clarity and places the quoted phrase in single quotes.
```

(ChatGPT is not proof, and quotes are not used elsewhere in such contexts, I am just giving it as another witness.)

Note, too, the capitalization of the first word "All" in the quoted statement. So the verse could read,

"But when he saith, All" instead of "But when he saith all".

**Comment by asylumcs** [comment]
What it "could read" is not something I can act upon. If you are suggesting a correction, please be very clear what you want to change. We are not modernizing; we do not ask ChatGPT what punctuation should be there. We would like to preserve this book the way it was printed to the best of our ability. Please answer back if you are suggesting we change the posted version.

**Comment by smichr** [comment]
I don't have access to multiple printed copies of different versions, so I will just note that my printed KJV agrees with version 30, and version 30 differs from the authorized (e-version) which introduces a comma after "saith" but has no capital "a".  Could you review against the printed copies that you have?

I am also not sure what you mean by "not modernizing" since spellings differ between different versions (rasor vs razor, cieling vs ceiling, instructer vs instructor). With what version are you trying to maintain fidelity?

When it comes to punctuation and letter case, I think I will just avoid making any suggestions. There is a certain genius in having Greek and Hebrew, with neither capitals nor punctuation, be the language for the original scriptures :-)

**Comment by gbnewby** [comment]
This PG eBook was created long ago, and we don't have a reference print source. You might instead find a reference print source scan set on sites such as Google Books or The Internet Archive. 

You might have already seen our general guidance here: https://www.gutenberg.org/help/errata.html

We are a small team and don't have the time or expertise to investigate potential variations. Instead, we rely on you, the reporter, to do the research that demonstrates a change should be made.

Concerning typography, capitalization, spelling, etc.: When a book is reprinted many times, it's typical for variations to creep in. It's reasonable to think that some print editions (or online) are actually derived from our #30, in addition to the print source(s) of our #30 being derived from prior printings over, in this situation, hundreds of years.

When combined with the specific history of this book (going back millennia, with multiple translations), it's not surprising to find typographical variations. From PG's point of view, we do not promise to adhere to a particular print edition. Basically what this means is that it probably doesn't make sense to try to align #30 with a particular print edition. Instead, try to focus on actual typos or formatting issues.

Thanks for your help with improving #30!

Dr. Gregory B. Newby
Chief Executive and Director
Project Gutenberg Literary Archive Foundation www.gutenberg.org
A 501(c)(3) not-for-profit organization with EIN 64-6221541

**Comment by asylumcs** [comment]
I will close this issue. However, if there is a specific correction to be made regarding the comma after "saith", please reopen this issue along with specifically what you feel should be changed.
