### ISSUE TITLE
compound words

### ISSUE THREAD

**Issue by smichr** [gutenbergbooks/30#9]
It is not clear to me what the target is for the forms of the words that appear or how one would determine *how* compounds words like the following should appear. So this is an issue for discussion. I would be happy to open a PR for the changes if I could get some feedback on what is desired. The numbers in the 2nd and 3rd column are the number of times the form of the word in column 1 appears in the G30 or Authorized versions, respectively.
```
----------------  ---  ----------
word              G30  Authorized
----------------  ---  ----------
first born        4    0
firstborn         113  117

anything          5    0
any thing         141  146

bow shot          1    0
bowshot           0    1

today             2    0
to day            76   78

menchildren       1    0
men children      3    4

tomorrow          1    0
to morrow         55   56

everything        2    0
every thing       32   34

house tops        1    0
housetops         7    8

house top         2    1
housetop          14   15

day time          7    3
daytime           3    7

noon day          3    1
noonday           7    9

couching place    1    0
couchingplace     0    1

fellow disciples  1    0
fellowdisciples   0    1
----------------  ---  ----------
````

With regard to @gbnewby comment [here](https://github.com/gutenbergbooks/30/issues/6#issuecomment-2405627630) "From PG's point of view, we do not promise to adhere to a particular print edition. Basically what this means is that it probably doesn't make sense to try to align #30 with a particular print edition. Instead, try to focus on actual typos or formatting issues." it is not clear whether the above should be considered as typos or not.

If you would prefer, for tracking purposes, that I open issues for each word, I can do that, too.

**Comment by gbnewby** [comment]
Hi Christopher. Thanks for your continued interest in improving #30. From
your list, it seems likely that some of the mismatches are typos, and some
are not. It's up to you to do the research on this, which would likely
include consulting printed resources that are not based on #30. Luckily
there are plenty of print versions of the KJV for you to select from.

The PG errata team doesn't do the research for stuff like this. It's up to
you, the reporter. We definitely don't want a bunch more issues or separate
PRs. The preference is for you to do all your research, then submit a
single PR with your proposed changes. Thanks again.

**Comment by asylumcs** [comment]
I'll close this issue. If there are specific corrections in the future as Greg mentioned, please open a new issue or a PR.
